// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featuredblog: dynamic(() => import("./Featuredblog")),
  hero: dynamic(() => import("./Hero")),
  popular_blog: dynamic(() => import("./PopularBlog")),
  recentblog: dynamic(() => import("./Recentblog")),
};
